stages:
  - build

windows-i2c:
  stage: build

  tags:
    - shared-windows
    - windows
    - windows-1809

  variables:
    STACK_ROOT: "c:\\stack_root"

  cache:
    key: stack-root-$CI_JOB_NAME
    paths:
      - "c:\\stack_root"

  script:
    - |

      $computersys = Get-WmiObject Win32_ComputerSystem -EnableAllPrivileges;
      $computersys.AutomaticManagedPagefile = $False;
      $computersys.Put();

      $pagefile = Get-WmiObject -Query "Select * From Win32_PageFileSetting Where Name like '%pagefile.sys'";
      $pagefile.InitialSize = 8192;
      $pagefile.MaximumSize = 16384;
      $pagefile.Put();

      Get-WmiObject WIN32_Pagefile | Select-Object Name, InitialSize, MaximumSize, FileSize 
      systeminfo /fo csv | ConvertFrom-Csv | select OS*, System*, Hotfix* | Format-List
      certutil –addstore -enterprise –f "Root" .ci/gitlab/dst-root-ca-x3.pem
      choco install -y haskell-stack
      refreshenv
      stack build -j1 --ghc-options=-j1

