stages:
  - build_and_test
  - publish

# Haddock, doctests, unittests, clash-dev testing. These are single threaded
# tests and therefore suitable for public runners.
.tests:
  stage: build_and_test
  trigger: 
    include:
      - local: /.ci/gitlab/pipeline.yml
    strategy: depend
  variables:
    UPSTREAM_CI_JOB_NAME: $CI_JOB_NAME

tests-8.8.3:
  extends: .tests
