stages:
  - build

windows-i2c:
  stage: build

  tags:
    - shared-windows
    - windows
    - windows-1809

  variables:
    STACK_ROOT: "c:\\stack_root"

  cache:
    key: stack-root-$CI_JOB_NAME
    paths:
      - "c:\\stack_root"

  script:
    - |
      $pagefile = Get-WmiObject Win32_PagefileSetting | Where-Object {$_.name -eq "C:\pagefile.sys"}
      $pagefile.delete() 

      $Pagefile = Get-WmiObject Win32_PagefileSetting
      $pagefile.Name = "C:\pagefile.sys"
      $pagefile.Caption = "C:\pagefile.sys"
      $pagefile.Description = "'pagefile.sys' @ C:"
      $pagefile.SettingID ="pagefile.sys @ C:"
      $pagefile.InitialSize = 16000
      $pagefile.MaximumSize = 32000
      $pagefile.put()

      Get-WmiObject WIN32_Pagefile | Select-Object Name, InitialSize, MaximumSize, FileSize 
      systeminfo /fo csv | ConvertFrom-Csv | select OS*, System*, Hotfix* | Format-List
      certutil –addstore -enterprise –f "Root" .ci/gitlab/dst-root-ca-x3.pem
      choco install -y haskell-stack
      refreshenv
      stack build -j1 --ghc-options=-j1

